### ISSUE TITLE
Segfault on MIPS

### ISSUE THREAD

**Issue by tosiara** [AlexanderOMara/wireguard-go-builds#1]
I get this segfault on an older MIPS device:
```
# ./wireguard-go 
futexwakeup addr=0x2a45f4 returned -89
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x3cdec]

runtime stack:
runtime.throw(0x1ad4b4, 0x2a)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:608 +0x60
runtime.sigpanic()
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/signal_unix.go:374 +0x3b0
runtime.futexwakeup(0x2a45f4, 0x1)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/os_linux.go:81 +0x8c
runtime.notewakeup(0x2a45f4)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/lock_futex.go:136 +0x68
runtime.startlockedm(0x4000e0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/proc.go:2194 +0x90
runtime.schedule()
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/proc.go:2626 +0x74
runtime.mstart1()
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/proc.go:1292 +0xbc
runtime.mstart()
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/proc.go:1248 +0x68

goroutine 1 [running, locked to thread]:
	goroutine running on other thread; stack unavailable
```
Searching on the internet shows that this may be related to MIPS soft-float and missing FPU.

Do you know if there is a solution without recompiling the kernel?

Thanks

**Comment by AlexanderOMara** [comment]
I'd suggest trying the latest version from the official channels.

This isn't an official repo nor do I develop wireguard-go, I just make this an experiment to build some wireguard-go binaries a while back.
